---

sudo: true

language: python

python:
  - 2.7

services:
  - docker

install:
  - pip install --upgrade pip
  - curl https://raw.githubusercontent.com/timorunge/docker-test-runner/master/install.sh | sh

script:
  - ./docker_test_runner.py -f tests/docker_test_runner.travis.yml -t 2

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
