---

version: '2'
services:
  centos_7:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_CentOS_7
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
  debian_9_4:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Debian_9.4
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
  ubuntu_16_04:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_16.04
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
  ubuntu_18_04:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_18.04
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.custom_nginx
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
