---

sudo: true

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

services:
  - docker

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

script:
  - docker-compose -f .travis-docker-compose.yml config
  - docker-compose -f .travis-docker-compose.yml pull
  - docker-compose -f .travis-docker-compose.yml build
  - docker-compose -f .travis-docker-compose.yml up --no-start
  - docker-compose -f .travis-docker-compose.yml up
  - docker-compose -f .travis-docker-compose.yml down

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
