---

- name: Build nginx (with patches)
  args:
    chdir: "{{ custom_nginx_install_dir }}/build/nginx-{{ custom_nginx_version }}"
  command: "./configure {{ custom_nginx_build_options | join(' ') }}"
  when: >
        (custom_nginx_checksum_catalog.changed) or
        (custom_nginx_patches.changed) or
        (custom_nginx_source_files.changed)
  register: custom_nginx_build
