---

- name: Install nginx build dependencies
  package:
    name: "{{ custom_nginx_dependency_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
  delay: 10
  register: result
  retries: 3
  until: result is succeeded

- name: Create required directories
  file:
    mode: 0755
    path: "{{ item }}"
    state: directory
  loop: "{{ custom_nginx_all_directories | flatten(levels=1) }}"

- name: Create nginx group
  group:
    name: "{{ custom_nginx_group }}"
    state: present

- name: Create nginx user
  user:
    create_home: no
    groups: "{{ custom_nginx_group }}"
    name: "{{ custom_nginx_user }}"
    shell: /bin/false
