---

- name: Generate directory list out of single directories
  set_fact:
    custom_nginx_single_directories:
      - "{{ custom_nginx_prefix_directory }}"
      - "{{ custom_nginx_log_directory }}"
      - "{{ custom_nginx_cache_directory }}"
      - "{{ custom_nginx_modules_directory }}"
      - "{{ custom_nginx_install_dir }}/build"
      - "{{ custom_nginx_install_dir }}/download"
      - "{{ custom_nginx_install_dir }}/mercurial"
      - "{{ custom_nginx_install_dir }}/tmp"

- name: Generate complete directory list
  set_fact:
    custom_nginx_all_directories: "{{ custom_nginx_single_directories }} + {{ custom_nginx_additional_directories | default(omit) }}"

- name: Set nginx service status
  set_fact:
    custom_nginx_service_state: stopped
  when: not custom_nginx_service_enabled
