---

- name: Compile custom nginx
  make:
    chdir: "{{ custom_nginx_install_dir }}/build/nginx-{{ custom_nginx_version }}"
  register: custom_nginx_compile
  when: custom_nginx_build.changed

- name: Install custom nginx
  make:
    chdir: "{{ custom_nginx_install_dir }}/build/nginx-{{ custom_nginx_version }}"
    target: install
  notify:
    - systemctl daemon-reload
    - restart nginx
  when: custom_nginx_compile.changed
