- name: Create a directory if it does not exist
  file:
    path: "{{ custom_nginx_static_modules_directory }}"
    state: directory
    mode: '0755'

- name: install nginx modules from git 
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ custom_nginx_static_modules_directory }}/item.value.name"
    version: "{{ item.value.version | default(master) }}"
  loop: "{{ custom_nginx_modules | dict2items }}"
  register: custom_nginx_modules
  when: custom_nginx_modules is defined